twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        App\Modules\RentalProperty\Component\: 'App\Modules\RentalProperty\Component'
        App\Modules\Base\Component\: 'App\Modules\Base\Component'
